In [1]:
import numpy as np

In [2]:
a = np.ones([2, 3])* 2
b = np.ones([2, 3]) * 3
a+b

array([[5., 5., 5.],
       [5., 5., 5.]])

In [3]:
np.add(a, b)

array([[5., 5., 5.],
       [5., 5., 5.]])

In [4]:
c = np.array([1, 2, 3], dtype = complex);
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [5]:
i=1

In [6]:
rg = np.random.default_rng(1)
rg.random((2, 3))

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [7]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [8]:
import asyncio

In [ ]:
;